server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8114/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: data-service

feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 5000
  OkToRetryOnAllOperations: true



